### ISSUE TITLE
Remove Trailing Return Type Syntax

### ISSUE THREAD

**Issue by mkristien** [Hyp-ed/styleguide#1]
Trailing Return Type Syntax is almost never used and only confuses people. I suggest removing this from style-guide on the grounds of being unnecessary.

**Comment by brano2** [comment]
I don't really care. The section is at the end anyway. And it might be useful in showing people that there actually is this neater syntax in some cases.

Also, for the future, it's useful to include a [link to the relevant section](https://hyp-ed.github.io/styleguide/#trailing_return) so people can easily find what we are talking about. You can do this by clicking the little chain icon next to the section heading and copying the URL from your browser.

**Comment by brano2** [comment]
So this passed as there is a positive difference of 3 or more votes. Can someone make a PR for it? @mkristien
