### ISSUE TITLE
Remove Lambda Expressions

### ISSUE THREAD

**Issue by mkristien** [Hyp-ed/styleguide#3]
It anybody even using these?

React with :+1: if you want to remove the [section on lambdas](https://hyp-ed.github.io/styleguide/#Formatting_Lambda_Expressions) from the styleguide (they can still be used in the code). React with :-1: if you want to keep it in the styleguide.

**Comment by neilweidinger** [comment]
Yea I agree, this is actually probs a good candidate for removal

**Comment by georgeka98** [comment]
That's the only one which I may disagree on. Sometimes I tend to use lambda functions for self explanatory code blocks such as array mappings etc in dynamic programming languages such as Python. Chances are I may start using them in C++ too, If I feel like similar self explanatory functions will be used, as it will only reduce the amount of lines.

**Comment by mkristien** [comment]
This is not saying we should forbid lambdas. Instead, it is saying we do not have a description of style-guide for lambdas since few people use them. Make the style-guide simple.

**Comment by brano2** [comment]
@mkristien @georgeka98 @neilweidinger can you please vote on the first comment again so the votes are easy to count?
